# Do NOT update manually; changes here will be overwritten by Copier
_commit: v2.2.1
_src_path: https://github.com/coopiteasy/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: OCB
odoo_version: 12.0
org_name: Coop IT Easy SC
org_slug: coopiteasy
rebel_module_groups:
- account_invoice_ubl_mass_download
repo_description: TODO
repo_name: IT management tools for the social economy
repo_slug: addons
repo_website: https://coopiteasy.be

