# Do NOT update manually; changes here will be overwritten by Copier
_commit: v2.0.10
_src_path: https://github.com/coopiteasy/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Coop IT Easy SC
org_slug: coopiteasy
rebel_module_groups:
- account_invoice_ubl_mass_download
repo_description: TODO
repo_name: IT management tools for the social economy
repo_slug: addons
repo_website: https://coopiteasy.be
travis_apt_packages: []
travis_apt_sources: []
