from . import partner
from . import product
from . import resource_activity
from . import resource_activity_lang
from . import resource_activity_registration
from . import resource_activity_theme
from . import resource_activity_type
from . import resource_allocation
from . import resource_available
from . import resource_category
from . import resource_location
from . import sale_order
