from . import partner
from . import resource_activity
from . import resource_activity_registration
from . import resource_activity_delivery
from . import sale
from . import resource
from . import opening_hours
from . import opening_hours_day
from . import terms_conditions
from . import sale_note
