# -*- coding: utf-8 -*-
# © 2017 Coop IT Easy (http://www.coopiteasy.be)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Website Sale Order BBA',
    'category': 'E-Commerce',
    'author': "Coop IT Easy - Houssine BAKKALI <houssine@coopiteasy.be>",
    'website': 'www.coopiteasy.be',
    'version': '11.0.1.0.0',
    'license': 'AGPL-3',
    'depends': [
        'website_sale',
        'l10n_be_invoice_bba'
    ],
    "description": """
    This module enable the bba structured communication on the sale order
    generated by the e-commerce.
    """,
    'data': [
    ],
    'installable': True,
}
